filter:
    excluded_paths:
        - 'tests/*'
checks:
    php: true
coding_style:
    php:
        indentation:
            general:
                size: 1
        spaces:
            around_operators:
                concatenation: true
build:
    tests:
        override:
            -
                command: 'php bin/phpunit --coverage-clover=coverage.xml --exclude-group integration'
                coverage:
                    file: 'coverage.xml'
                    format: 'clover'