index:
    path: /
    defaults: { _controller: 'App\Controller\HomeController::index' }
    methods: [GET]
searchPlayer:
    path: /
    defaults: { _controller: 'App\Controller\HomeController::searchPlayer' }
    methods: [POST]
